# Generated by Django 3.2.3 on 2021-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='nombreC',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre del cliente'),
        ),
    ]
