# Generated by Django 3.2.3 on 2021-06-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehiculo_nombrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='correo',
            field=models.CharField(max_length=40, null=True, verbose_name='Correo electronico'),
        ),
    ]
