# Generated by Django 3.2.5 on 2021-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210717_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumerIdentificador', models.IntegerField()),
                ('NombreC', models.CharField(max_length=30, null=True, verbose_name='Nombre Completo')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('Telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
