# Generated by Django 3.2.5 on 2021-07-17 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vehiculo_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='NumerIdentificador',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='NumeroIdentificador',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Numero Identificador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='Telefono',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
